#!/usr/bin/env bash

# Credits to Perosar for Paraphrasing the script
# t.me/@Pero_Sar1111

pulseaudio --start > /dev/null 2>&1
case "$1" in
	start)
		bash "$(realpath "$0")" stop
		pactl load-module module-simple-protocol-tcp rate=48000 format=s16le channels=2 source=auto_null.monitor record=true port=8000
		;;
	stop)
		plist=$(pactl list | grep tcp -B1 | grep M | sed 's/[^0-9]//g')
		[ -n "$plist" ] && pactl unload-module "$plist"
		;;
	*)
		echo "Usage: $0 start|stop" >&2
		;;
esac
